# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
{
    "name": "SPP Commcare Integration",
    "category": "OpenSPP",
    "version": "15.0.0.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/openspp/openspp-commcare",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "base",
        "g2p_registry_base",
        "g2p_registry_individual",
        "g2p_registry_group",
        "g2p_registry_membership",
        "g2p_programs",
        "g2p_bank",
        "queue_job",
        "base_rest",
        "component",
        "extendable",
    ],
    "external_dependencies": {"python": []},
    'data': [
        'security/ir.model.access.csv',
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
